// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDAL.Models;

namespace TestDAL.Migrations
{
    [DbContext(typeof(JTITestContext))]
    partial class JTITestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestDAL.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bussines Development"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Human Resource"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Purchase"
                        });
                });

            modelBuilder.Entity("TestDAL.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Vasya",
                            LastName = "Solovyov"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Oleg",
                            LastName = "Vidin"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Egor",
                            LastName = "Aleksandrov"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Johan",
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Oleg",
                            LastName = "Prokofiev"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Leon",
                            LastName = "Martirasyan"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Vasya",
                            LastName = "Sokolov"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Seva",
                            LastName = "Vagshtein"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Aleksandr",
                            LastName = "Elistratov"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Vasiliy",
                            LastName = "Lozhkin"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Maksim",
                            LastName = "Belyaev"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Mikhail",
                            LastName = "Demchenko"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Olga",
                            LastName = "Vortonyan"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Ivan",
                            LastName = "Demushkin"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Irina",
                            LastName = "Zolotova"
                        });
                });

            modelBuilder.Entity("TestDAL.Models.Visits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            EmployeeId = 14
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 4,
                            EmployeeId = 5
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            EmployeeId = 2
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            EmployeeId = 9
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            EmployeeId = 10
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            EmployeeId = 10
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            EmployeeId = 7
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 1,
                            EmployeeId = 5
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 2,
                            EmployeeId = 10
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 4,
                            EmployeeId = 4
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 5,
                            EmployeeId = 7
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 2,
                            EmployeeId = 8
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 3,
                            EmployeeId = 9
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 4,
                            EmployeeId = 3
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 2,
                            EmployeeId = 2
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 4,
                            EmployeeId = 8
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 5,
                            EmployeeId = 9
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 1,
                            EmployeeId = 11
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 2,
                            EmployeeId = 13
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 3,
                            EmployeeId = 10
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 3,
                            EmployeeId = 9
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 4,
                            EmployeeId = 8
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 4,
                            EmployeeId = 7
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 5,
                            EmployeeId = 2
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 6,
                            EmployeeId = 15
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 1,
                            EmployeeId = 12
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 2,
                            EmployeeId = 1
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 4,
                            EmployeeId = 9
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 5,
                            EmployeeId = 10
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 3,
                            EmployeeId = 1
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 2,
                            EmployeeId = 3
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 2,
                            EmployeeId = 4
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 2,
                            EmployeeId = 5
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 6,
                            EmployeeId = 6
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 2,
                            EmployeeId = 6
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 1,
                            EmployeeId = 7
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 3,
                            EmployeeId = 15
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 3,
                            EmployeeId = 14
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 4,
                            EmployeeId = 13
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 5,
                            EmployeeId = 12
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 6,
                            EmployeeId = 10
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 5,
                            EmployeeId = 9
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 3,
                            EmployeeId = 8
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 3,
                            EmployeeId = 7
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 4,
                            EmployeeId = 6
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 1,
                            EmployeeId = 5
                        });
                });

            modelBuilder.Entity("TestDAL.Models.Visits", b =>
                {
                    b.HasOne("TestDAL.Models.Departments", "Department")
                        .WithMany("Visits")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Visits_Departments")
                        .IsRequired();

                    b.HasOne("TestDAL.Models.Employees", "Employee")
                        .WithMany("Visits")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Visits_Employees")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
